COUNTRIES = [
    'China',
    'Europe',
    'France',
    'Germany',
    'Italy',
    'Japan',
    'Switzerland',
    'United Kingdom',
    'United States',
    'World'
]
SOURCES = {
    "export_partners_data": "../data/raw/no_of_products_and_countries_exports",
    "import_partners_data": "../data/raw/no_of_products_and_countries_imports",
    "trade_data": "../data/raw/trade_summary",
    "market_data": "../data/raw/market_data.xlsx",
    "sales_data":  "../data/raw/sales_data.csv"
}

MARKET_SERIES = [
    'production_index_machinery_electricals',
    'shipments_index_machinery_electricals', 
    'price_of_base_metals', 
    'price_of_energy', 
    'price_of_metals_minerals', 
    'price_of_natural_gas_index', 
    'price_of_crude_oil_average', 
    'price_of_copper',
    'eur_in_lcu', 
    'electrical_equipment_producer_prices', 
    'machinery_and_equipment_nec_production_index', 
    'electrical_equipment_production_index'
]

SALES_SERIES = [
    'product_group_1_sales', 
    'product_group_11_sales', 
    'product_group_6_sales', 
    'product_group_8_sales', 
    'product_group_12_sales', 
    'product_group_16_sales', 
    'product_group_4_sales', 
    'product_group_5_sales', 
    'product_group_3_sales', 
    'product_group_9_sales',
    'product_group_14_sales', 
    'product_group_13_sales', 
    'product_group_20_sales', 
    'product_group_36_sales'
]

PARTNER_SERIES = [
    'n_partners_imports',
    'n_products_imports',
    'n_partners_exports',
    'n_products_exports'
]

TRADE_SERIES = [
    'germany_all_products_trade_usd_mil_top_5_import_partner',
    'germany_all_products_trade_usd_mil_top_5_export_partner',
    'germany_all_products_partner_share_top_5_import_partner', 
    'germany_all_products_partner_share_top_5_export_partner', 
    'world_consumer_goods_export_usd_mil', 
    'world_minerals_export_usd_mil', 
    'world_raw_materials_export_usd_mil',
    'world_capital_goods_export_usd_mil', 
    'world_plastic_or_rubber_export_usd_mil', 
    'united_kingdom_all_products_trade_usd_mil_top_5_import_partner', 
    'world_vegetable_export_usd_mil', 
    'world_footwear_export_usd_mil', 
    'world_miscellaneous_export_usd_mil', 
    'china_all_products_trade_usd_mil_top_5_export_partner', 
    'france_all_products_trade_usd_mil_top_5_import_partner', 
    'world_intermediate_goods_export_usd_mil', 
    'world_textiles_and_clothing_export_usd_mil', 
    'world_food_products_export_usd_mil', 
    'world_consumer_goods_import_usd_mil', 
    'world_transportation_export_usd_mil', 
    'china_all_products_trade_usd_mil_top_5_import_partner', 
    'world_raw_materials_import_usd_mil', 
    'united_kingdom_all_products_trade_usd_mil_top_5_export_partner', 
    'world_hides_and_skins_export_usd_mil', 
    'france_all_products_trade_usd_mil_top_5_export_partner', 
    'italy_all_products_trade_usd_mil_top_5_export_partner', 
    'world_wood_export_usd_mil', 
    'world_mach_and_elec_export_usd_mil', 
    'world_metals_export_usd_mil', 
    'italy_all_products_trade_usd_mil_top_5_import_partner', 
    'world_all_products_duty_free_imports_us_thousand', 
    'world_stone_and_glass_export_usd_mil', 
    'world_intermediate_goods_import_usd_mil', 
    'united_states_all_products_trade_usd_mil_top_5_export_partner', 
    'united_states_all_products_trade_usd_mil_top_5_import_partner', 
    'world_all_products_imports_in_usd_mil', 
    'world_capital_goods_import_usd_mil', 
    'world_all_products_exports_in_usd_mil', 
    'world_fuels_export_usd_mil',
    'world_chemicals_export_usd_mil', 
    'world_animal_export_usd_mil', 
    'world_fuels_export_product_share', 
    'world_all_products_country_growth_', 
    'world_vegetable_export_product_share', 
    'united_states_all_products_partner_share_top_5_import_partner', 
    'world_footwear_export_product_share', 
    'world_capital_goods_weighted_average_', 
    'world_consumer_goods_import_product_share', 
    'world_raw_materials_weighted_average_', 
    'world_all_products_world_growth_', 
    'world_transportation_export_product_share', 
    'united_kingdom_all_products_partner_share_top_5_import_partner', 
    'world_capital_goods_import_product_share', 
    'world_food_products_export_product_share',
    'china_all_products_partner_share_top_5_import_partner', 
    'world_all_products_duty_free_tariff_lines_share_', 
    'world_metals_export_product_share', 
    'china_all_products_partner_share_top_5_export_partner', 
    'world_wood_export_product_share', 
    'world_intermediate_goods_export_product_share', 
    'world_intermediate_goods_weighted_average_', 
    'world_textiles_and_clothing_export_product_share', 
    'world_mach_and_elec_export_product_share', 
    'world_intermediate_goods_import_product_share', 
    'italy_all_products_partner_share_top_5_import_partner', 
    'world_hides_and_skins_export_product_share', 
    'world_minerals_export_product_share',
    'world_all_products_simple_average_', 
    'france_all_products_partner_share_top_5_export_partner', 
    'world_plastic_or_rubber_export_product_share', 
    'world_miscellaneous_export_product_share', 
    'france_all_products_partner_share_top_5_import_partner', 
    'world_all_products_maximum_rate_', 
    'world_all_products_weighted_average_', 
    'united_kingdom_all_products_partner_share_top_5_export_partner', 
    'world_raw_materials_export_product_share', 
    'italy_all_products_partner_share_top_5_export_partner', 
    'world_consumer_goods_weighted_average_', 
    'world_stone_and_glass_export_product_share', 
    'world_capital_goods_export_product_share', 
    'world_chemicals_export_product_share', 
    'united_states_all_products_partner_share_top_5_export_partner', 
    'world_consumer_goods_export_product_share', 
    'world_animal_export_product_share', 
    'world_raw_materials_import_product_share'
]

TRADE_SERIES_NEW = [
    'germany_all_products_trade_usd_mil_top_5_import_partner',
    'germany_all_products_trade_usd_mil_top_5_export_partner',
    'germany_all_products_partner_share_top_5_import_partner',
    'germany_all_products_partner_share_top_5_export_partner',
    'world_consumer_goods_export_usd_mil',
    'world_minerals_export_usd_mil',
    'world_raw_materials_export_usd_mil',
    'world_capital_goods_export_usd_mil',
    'world_plastic_or_rubber_export_usd_mil',
    'united_kingdom_all_products_trade_usd_mil_top_5_import_partner',
    'china_all_products_trade_usd_mil_top_5_export_partner',
    'france_all_products_trade_usd_mil_top_5_import_partner',
    'world_intermediate_goods_export_usd_mil',
    'world_consumer_goods_import_usd_mil',
    'world_transportation_export_usd_mil',
    'china_all_products_trade_usd_mil_top_5_import_partner',
    'world_raw_materials_import_usd_mil',
    'united_kingdom_all_products_trade_usd_mil_top_5_export_partner',
    'france_all_products_trade_usd_mil_top_5_export_partner',
    'italy_all_products_trade_usd_mil_top_5_export_partner',
    'world_mach_and_elec_export_usd_mil',
    'world_metals_export_usd_mil',
    'italy_all_products_trade_usd_mil_top_5_import_partner',
    'world_all_products_duty_free_imports_us_thousand',
    'world_intermediate_goods_import_usd_mil',
    'united_states_all_products_trade_usd_mil_top_5_export_partner',
    'united_states_all_products_trade_usd_mil_top_5_import_partner',
    'world_all_products_imports_in_usd_mil',
    'world_capital_goods_import_usd_mil',
    'world_all_products_exports_in_usd_mil',
    'world_fuels_export_usd_mil', 
    'world_chemicals_export_usd_mil',
    'world_fuels_export_product_share',
    'world_all_products_country_growth_',
    'united_states_all_products_partner_share_top_5_import_partner',
    'world_consumer_goods_import_product_share',
    'world_all_products_world_growth_',
    'world_transportation_export_product_share',
    'united_kingdom_all_products_partner_share_top_5_import_partner',
    'world_capital_goods_import_product_share',
    'china_all_products_partner_share_top_5_import_partner',
    'world_all_products_duty_free_tariff_lines_share_',
    'world_metals_export_product_share',
    'china_all_products_partner_share_top_5_export_partner',
    'world_intermediate_goods_export_product_share',
    'world_mach_and_elec_export_product_share',
    'world_intermediate_goods_import_product_share',
    'italy_all_products_partner_share_top_5_import_partner',
    'world_minerals_export_product_share',
    'france_all_products_partner_share_top_5_export_partner',
    'france_all_products_partner_share_top_5_import_partner',
    'united_kingdom_all_products_partner_share_top_5_export_partner',
    'world_raw_materials_export_product_share',
    'italy_all_products_partner_share_top_5_export_partner',
    'world_capital_goods_export_product_share',
    'world_chemicals_export_product_share',
    'united_states_all_products_partner_share_top_5_export_partner',
    'world_consumer_goods_export_product_share',
    'world_raw_materials_import_product_share'
]

LOG_SALES_SERIES = [
    'log_product_group_1_sales', 
    'log_product_group_6_sales',
    'log_product_group_5_sales', 
    'log_product_group_4_sales',
    'log_product_group_3_sales', 
    'log_product_group_11_sales',
    'log_product_group_14_sales', 
    'log_product_group_12_sales',
    'log_product_group_13_sales', 
    'log_product_group_16_sales',
    'log_product_group_9_sales', 
    'log_product_group_8_sales',
    'log_product_group_36_sales', 
    'log_product_group_20_sales'
]

STATIONARY_SERIES = [
    ('electrical_equipment_producer_prices', 'china'),
    ('germany_all_products_partner_share_top_5_export_partner', 'china'),
    ('germany_all_products_partner_share_top_5_import_partner', 'china'),
    ('germany_all_products_trade_usd_mil_top_5_export_partner', 'china'),
    ('germany_all_products_trade_usd_mil_top_5_import_partner', 'china'),
    ('n_partners_exports', 'china'),
    ('n_partners_imports', 'china'),
    ('n_products_exports', 'china'),
    ('production_index_machinery_electricals', 'china'),
    ('shipments_index_machinery_electricals', 'china'),
    ('production_index_machinery_electricals', 'europe'),
    ('shipments_index_machinery_electricals', 'europe'),
    ('electrical_equipment_production_index', 'france'),
    ('germany_all_products_partner_share_top_5_export_partner', 'france'),
    ('germany_all_products_partner_share_top_5_import_partner', 'france'),
    ('germany_all_products_trade_usd_mil_top_5_export_partner', 'france'),
    ('machinery_and_equipment_nec_production_index', 'france'),
    ('n_partners_exports', 'france'),
    ('n_partners_imports', 'france'),
    ('production_index_machinery_electricals', 'france'),
    ('shipments_index_machinery_electricals', 'france'),
    ('china_all_products_partner_share_top_5_export_partner', 'germany'),
    ('china_all_products_partner_share_top_5_import_partner', 'germany'),
    ('electrical_equipment_production_index', 'germany'),
    ('france_all_products_partner_share_top_5_export_partner', 'germany'),
    ('france_all_products_partner_share_top_5_import_partner', 'germany'),
    ('france_all_products_trade_usd_mil_top_5_export_partner', 'germany'),
    ('italy_all_products_partner_share_top_5_export_partner', 'germany'),
    ('italy_all_products_partner_share_top_5_import_partner', 'germany'),
    ('italy_all_products_trade_usd_mil_top_5_export_partner', 'germany'),
    ('machinery_and_equipment_nec_production_index', 'germany'),
    ('n_partners_exports', 'germany'),
    ('n_partners_imports', 'germany'),
    ('n_products_exports', 'germany'),
    ('n_products_imports', 'germany'),
    ('production_index_machinery_electricals', 'germany'),
    ('shipments_index_machinery_electricals', 'germany'),
    ('united_kingdom_all_products_partner_share_top_5_export_partner', 'germany'),
    ('united_kingdom_all_products_partner_share_top_5_import_partner', 'germany'),
    ('united_kingdom_all_products_trade_usd_mil_top_5_export_partner', 'germany'),
    ('united_kingdom_all_products_trade_usd_mil_top_5_import_partner', 'germany'),
    ('united_states_all_products_partner_share_top_5_export_partner', 'germany'),
    ('united_states_all_products_partner_share_top_5_import_partner', 'germany'),
    ('united_states_all_products_trade_usd_mil_top_5_export_partner', 'germany'),
    ('united_states_all_products_trade_usd_mil_top_5_import_partner', 'germany'),
    ('world_all_products_country_growth_', 'germany'),
    ('world_all_products_duty_free_tariff_lines_share_', 'germany'),
    ('world_all_products_exports_in_usd_mil', 'germany'),
    ('world_all_products_imports_in_usd_mil', 'germany'),
    ('world_all_products_world_growth_', 'germany'),
    ('world_capital_goods_export_usd_mil', 'germany'),
    ('world_capital_goods_import_product_share', 'germany'),
    ('world_chemicals_export_product_share', 'germany'),
    ('world_consumer_goods_export_product_share', 'germany'),
    ('world_consumer_goods_export_usd_mil', 'germany'),
    ('world_consumer_goods_import_product_share', 'germany'),
    ('world_consumer_goods_import_usd_mil', 'germany'),
    ('world_fuels_export_product_share', 'germany'),
    ('world_fuels_export_usd_mil', 'germany'),
    ('world_intermediate_goods_export_product_share', 'germany'),
    ('world_intermediate_goods_export_usd_mil', 'germany'),
    ('world_intermediate_goods_import_product_share', 'germany'),
    ('world_intermediate_goods_import_usd_mil', 'germany'),
    ('world_mach_and_elec_export_product_share', 'germany'),
    ('world_mach_and_elec_export_usd_mil', 'germany'),
    ('world_metals_export_product_share', 'germany'),
    ('world_metals_export_usd_mil', 'germany'),
    ('world_minerals_export_product_share', 'germany'),
    ('world_plastic_or_rubber_export_usd_mil', 'germany'),
    ('world_raw_materials_export_product_share', 'germany'),
    ('world_raw_materials_import_product_share', 'germany'),
    ('world_raw_materials_import_usd_mil', 'germany'),
    ('world_transportation_export_product_share', 'germany'),
    ('world_transportation_export_usd_mil', 'germany'),
    ('electrical_equipment_producer_prices', 'italy'),
    ('electrical_equipment_production_index', 'italy'),
    ('machinery_and_equipment_nec_production_index', 'italy'),
    ('n_partners_exports', 'italy'),
    ('n_partners_imports', 'italy'),
    ('n_products_imports', 'italy'),
    ('production_index_machinery_electricals', 'italy'),
    ('shipments_index_machinery_electricals', 'italy'),
    ('electrical_equipment_production_index', 'japan'),
    ('machinery_and_equipment_nec_production_index', 'japan'),
    ('n_partners_exports', 'japan'),
    ('n_partners_imports', 'japan'),
    ('n_products_exports', 'japan'),
    ('n_products_imports', 'japan'),
    ('production_index_machinery_electricals', 'japan'),
    ('shipments_index_machinery_electricals', 'japan'),
    ('electrical_equipment_production_index', 'switzerland'),
    ('machinery_and_equipment_nec_production_index', 'switzerland'),
    ('n_partners_exports', 'switzerland'),
    ('n_partners_imports', 'switzerland'),
    ('n_products_exports', 'switzerland'),
    ('n_products_imports', 'switzerland'),
    ('production_index_machinery_electricals', 'switzerland'),
    ('shipments_index_machinery_electricals', 'switzerland'),
    ('electrical_equipment_producer_prices', 'united kingdom'),
    ('electrical_equipment_production_index', 'united kingdom'),
    ('machinery_and_equipment_nec_production_index', 'united kingdom'),
    ('n_partners_exports', 'united kingdom'),
    ('n_partners_imports', 'united kingdom'),
    ('production_index_machinery_electricals', 'united kingdom'),
    ('shipments_index_machinery_electricals', 'united kingdom'),
    ('electrical_equipment_production_index', 'united states'),
    ('eur_in_lcu', 'united states'),
    ('germany_all_products_partner_share_top_5_export_partner', 'united states'),
    ('germany_all_products_partner_share_top_5_import_partner', 'united states'),
    ('germany_all_products_trade_usd_mil_top_5_export_partner', 'united states'),
    ('germany_all_products_trade_usd_mil_top_5_import_partner', 'united states'),
    ('machinery_and_equipment_nec_production_index', 'united states'),
    ('n_partners_exports', 'united states'),
    ('n_partners_imports', 'united states'),
    ('production_index_machinery_electricals', 'united states'),
    ('electrical_equipment_production_index', 'world'),
    ('machinery_and_equipment_nec_production_index', 'world'),
    ('n_partners_exports', 'world'),
    ('n_partners_imports', 'world'),
    ('n_products_exports', 'world'),
    ('n_products_imports', 'world'),
    ('price_of_base_metals', 'world'),
    ('price_of_copper', 'world'),
    ('price_of_crude_oil_average', 'world'),
    ('price_of_energy', 'world'),
    ('price_of_metals_minerals', 'world'),
    ('price_of_natural_gas_index', 'world')
 ]

HOMOSK_STAT_SERIES = [
    'production_index_machinery_electricals',
    'shipments_index_machinery_electricals',
    'price_of_base_metals',
    'price_of_energy',
    'price_of_metals_minerals',
    'price_of_natural_gas_index',
    'price_of_crude_oil_average',
    'price_of_copper',
    'eur_in_lcu',
    'electrical_equipment_producer_prices',
    'machinery_and_equipment_nec_production_index',
    'electrical_equipment_production_index',
    'n_partners_imports',
    'n_products_imports',
    'n_partners_exports',
    'n_products_exports',
    'germany_all_products_trade_usd_mil_top_5_import_partner',
    'germany_all_products_trade_usd_mil_top_5_export_partner',
    'germany_all_products_partner_share_top_5_import_partner',
    'germany_all_products_partner_share_top_5_export_partner',
    'world_consumer_goods_export_usd_mil',
    'world_minerals_export_usd_mil',
    'world_raw_materials_export_usd_mil',
    'world_capital_goods_export_usd_mil',
    'world_plastic_or_rubber_export_usd_mil',
    'united_kingdom_all_products_trade_usd_mil_top_5_import_partner',
    'china_all_products_trade_usd_mil_top_5_export_partner',
    'france_all_products_trade_usd_mil_top_5_import_partner',
    'world_intermediate_goods_export_usd_mil',
    'world_consumer_goods_import_usd_mil',
    'world_transportation_export_usd_mil',
    'china_all_products_trade_usd_mil_top_5_import_partner',
    'world_raw_materials_import_usd_mil',
    'united_kingdom_all_products_trade_usd_mil_top_5_export_partner',
    'france_all_products_trade_usd_mil_top_5_export_partner',
    'italy_all_products_trade_usd_mil_top_5_export_partner',
    'world_mach_and_elec_export_usd_mil',
    'world_metals_export_usd_mil',
    'italy_all_products_trade_usd_mil_top_5_import_partner',
    'world_all_products_duty_free_imports_us_thousand',
    'world_intermediate_goods_import_usd_mil',
    'united_states_all_products_trade_usd_mil_top_5_export_partner',
    'united_states_all_products_trade_usd_mil_top_5_import_partner',
    'world_all_products_imports_in_usd_mil',
    'world_capital_goods_import_usd_mil',
    'world_all_products_exports_in_usd_mil',
    'world_fuels_export_usd_mil',
    'world_chemicals_export_usd_mil',
    'world_fuels_export_product_share',
    'world_all_products_country_growth_',
    'united_states_all_products_partner_share_top_5_import_partner',
    'world_consumer_goods_import_product_share',
    'world_all_products_world_growth_',
    'world_transportation_export_product_share',
    'united_kingdom_all_products_partner_share_top_5_import_partner',
    'world_capital_goods_import_product_share',
    'china_all_products_partner_share_top_5_import_partner',
    'world_all_products_duty_free_tariff_lines_share_',
    'world_metals_export_product_share',
    'china_all_products_partner_share_top_5_export_partner',
    'world_intermediate_goods_export_product_share',
    'world_mach_and_elec_export_product_share',
    'world_intermediate_goods_import_product_share',
    'italy_all_products_partner_share_top_5_import_partner',
    'world_minerals_export_product_share',
    'france_all_products_partner_share_top_5_export_partner',
    'france_all_products_partner_share_top_5_import_partner',
    'united_kingdom_all_products_partner_share_top_5_export_partner',
    'world_raw_materials_export_product_share',
    'italy_all_products_partner_share_top_5_export_partner',
    'world_capital_goods_export_product_share',
    'world_chemicals_export_product_share',
    'united_states_all_products_partner_share_top_5_export_partner',
    'world_consumer_goods_export_product_share',
    'world_raw_materials_import_product_share'
]

SALES_COINTEGRATED_FEATURES = {
    'product_group_1_sales': [
        ('electrical_equipment_production_index', 'united kingdom'),
        ('electrical_equipment_producer_prices', 'united kingdom'),
        ('n_products_imports', 'switzerland'),
        ('production_index_machinery_electricals', 'china'),
        ('production_index_machinery_electricals', 'united kingdom'),
        ('n_partners_exports', 'switzerland'),
        ('n_products_imports', 'france'),
        ('n_products_exports', 'italy'),
        ('n_partners_exports', 'france'),
        ('machinery_and_equipment_nec_production_index', 'switzerland'),
        ('n_products_exports', 'world'),
        ('germany_all_products_partner_share_top_5_export_partner', 'united states'),
        ('germany_all_products_trade_usd_mil_top_5_export_partner', 'united states'),
        ('n_partners_imports', 'switzerland'),
        ('n_products_exports', 'japan'),
        ('price_of_energy', 'world'),
        ('machinery_and_equipment_nec_production_index', 'france'),
        ('n_products_exports', 'china'),
        ('price_of_metals_minerals', 'world'),
        ('production_index_machinery_electricals', 'switzerland'),
        ('shipments_index_machinery_electricals', 'italy'),
        ('n_partners_imports', 'france'),
        ('electrical_equipment_production_index', 'france'),
        ('n_products_exports', 'united kingdom'),
        ('germany_all_products_partner_share_top_5_export_partner', 'china'),
        ('shipments_index_machinery_electricals', 'japan'),
        ('germany_all_products_trade_usd_mil_top_5_export_partner', 'china'),
        ('shipments_index_machinery_electricals', 'united kingdom'),
        ('shipments_index_machinery_electricals', 'china'),
        ('production_index_machinery_electricals', 'france'),
        ('eur_in_lcu', 'united states'),
        ('price_of_base_metals', 'world'),
        ('germany_all_products_trade_usd_mil_top_5_import_partner', 'france'),
        ('production_index_machinery_electricals', 'united states'),
        ('n_products_exports', 'switzerland'),
        ('shipments_index_machinery_electricals', 'europe'),
        ('n_products_exports', 'france'),
        ('n_products_imports', 'italy'),
        ('n_products_imports', 'world'),
        ('n_partners_exports', 'italy'),
        ('shipments_index_machinery_electricals', 'switzerland'),
        ('n_products_imports', 'japan'),
        ('n_partners_exports', 'japan'),
        ('n_partners_exports', 'world'),
        ('n_products_imports', 'china'),
        ('machinery_and_equipment_nec_production_index', 'united states'),
        ('n_partners_exports', 'china'),
        ('n_products_imports', 'united kingdom'),
        ('electrical_equipment_production_index', 'italy'),
        ('electrical_equipment_producer_prices', 'italy'),
        ('n_partners_imports', 'world'),
        ('n_partners_exports', 'united kingdom'),
        ('price_of_natural_gas_index', 'world'),
        ('production_index_machinery_electricals', 'italy'),
        ('price_of_copper', 'world'),
        ('electrical_equipment_production_index', 'japan'),
        ('electrical_equipment_production_index', 'world'),
        ('n_partners_imports', 'united kingdom'),
        ('n_partners_imports', 'china'),
        ('machinery_and_equipment_nec_production_index', 'united kingdom')
    ], 'product_group_11_sales': [
        ('electrical_equipment_production_index', 'united kingdom'),
        ('electrical_equipment_producer_prices', 'united kingdom'),
        ('n_products_imports', 'switzerland'),
        ('production_index_machinery_electricals', 'china'),
        ('production_index_machinery_electricals', 'united kingdom'),
        ('n_partners_exports', 'switzerland'),
        ('n_products_imports', 'france'),
        ('n_products_exports', 'italy'),
        ('n_products_exports', 'world'),
        ('machinery_and_equipment_nec_production_index', 'switzerland'),
        ('germany_all_products_partner_share_top_5_export_partner', 'united states'),
        ('germany_all_products_trade_usd_mil_top_5_export_partner', 'united states'),
        ('n_partners_imports', 'switzerland'),
        ('n_products_exports', 'japan'),
        ('price_of_energy', 'world'),
        ('germany_all_products_partner_share_top_5_import_partner', 'france'),
        ('machinery_and_equipment_nec_production_index', 'france'),
        ('n_products_exports', 'china'),
        ('price_of_metals_minerals', 'world'),
        ('production_index_machinery_electricals', 'switzerland'),
        ('n_partners_imports', 'france'),
        ('shipments_index_machinery_electricals', 'italy'),
        ('electrical_equipment_production_index', 'france'),
        ('n_products_exports', 'united kingdom'),
        ('germany_all_products_partner_share_top_5_export_partner', 'china'),
        ('shipments_index_machinery_electricals', 'japan'),
        ('germany_all_products_trade_usd_mil_top_5_export_partner', 'china'),
        ('shipments_index_machinery_electricals', 'united kingdom'),
        ('price_of_crude_oil_average', 'world'),
        ('shipments_index_machinery_electricals', 'china'),
        ('production_index_machinery_electricals', 'france'),
        ('eur_in_lcu', 'united states'),
        ('price_of_base_metals', 'world'),
        ('germany_all_products_trade_usd_mil_top_5_import_partner', 'france'),
        ('production_index_machinery_electricals', 'united states'),
        ('n_products_exports', 'switzerland'),
        ('shipments_index_machinery_electricals', 'europe'),
        ('n_products_exports', 'france'),
        ('n_products_imports', 'italy'),
        ('n_products_imports', 'world'),
        ('n_partners_exports', 'italy'),
        ('shipments_index_machinery_electricals', 'switzerland'),
        ('n_partners_exports', 'united states'),
        ('n_products_imports', 'japan'),
        ('n_partners_exports', 'japan'),
        ('n_partners_exports', 'world'),
        ('n_products_imports', 'china'),
        ('machinery_and_equipment_nec_production_index', 'united states'),
        ('n_partners_exports', 'china'),
        ('n_products_imports', 'united kingdom'),
        ('electrical_equipment_production_index', 'italy'),
        ('electrical_equipment_producer_prices', 'italy'),
        ('n_partners_imports', 'world'),
        ('n_partners_exports', 'united kingdom'),
        ('price_of_natural_gas_index', 'world'),
        ('production_index_machinery_electricals', 'italy'),
        ('n_partners_imports', 'japan'),
        ('price_of_copper', 'world'),
        ('electrical_equipment_production_index', 'japan'),
        ('electrical_equipment_production_index', 'world'),
        ('n_partners_imports', 'united kingdom'),
        ('n_partners_imports', 'china')
    ], 'product_group_6_sales': [
        ('electrical_equipment_production_index', 'united kingdom'),
        ('electrical_equipment_producer_prices', 'united kingdom'),
        ('n_products_imports', 'switzerland'),
        ('production_index_machinery_electricals', 'china'),
        ('production_index_machinery_electricals', 'united kingdom'),
        ('n_partners_exports', 'switzerland'),
        ('n_products_imports', 'france'),
        ('n_products_exports', 'italy'),
        ('n_partners_exports', 'france'),
        ('machinery_and_equipment_nec_production_index', 'switzerland'),
        ('n_products_exports', 'world'),
        ('germany_all_products_partner_share_top_5_export_partner', 'united states'),
        ('germany_all_products_trade_usd_mil_top_5_export_partner', 'united states'),
        ('n_partners_imports', 'switzerland'),
        ('n_products_exports', 'japan'),
        ('price_of_energy', 'world'),
        ('machinery_and_equipment_nec_production_index', 'france'),
        ('n_products_exports', 'china'),
        ('price_of_metals_minerals', 'world'),
        ('production_index_machinery_electricals', 'switzerland'),
        ('shipments_index_machinery_electricals', 'italy'),
        ('n_partners_imports', 'france'),
        ('electrical_equipment_production_index', 'france'),
        ('n_products_exports', 'united kingdom'),
        ('germany_all_products_partner_share_top_5_export_partner', 'china'),
        ('shipments_index_machinery_electricals', 'japan'),
        ('germany_all_products_trade_usd_mil_top_5_export_partner', 'china'),
        ('shipments_index_machinery_electricals', 'united kingdom'),
        ('price_of_crude_oil_average', 'world'),
        ('shipments_index_machinery_electricals', 'china'),
        ('production_index_machinery_electricals', 'france'),
        ('eur_in_lcu', 'united states'),
        ('price_of_base_metals', 'world'),
        ('germany_all_products_trade_usd_mil_top_5_import_partner', 'france'),
        ('production_index_machinery_electricals', 'united states'),
        ('n_products_exports', 'switzerland'),
        ('shipments_index_machinery_electricals', 'europe'),
        ('n_products_exports', 'france'),
        ('n_products_imports', 'italy'),
        ('n_products_imports', 'world'),
        ('shipments_index_machinery_electricals', 'switzerland'),
        ('n_partners_exports', 'united states'),
        ('n_products_imports', 'japan'),
        ('n_partners_exports', 'japan'),
        ('n_partners_exports', 'world'),
        ('n_products_imports', 'china'),
        ('machinery_and_equipment_nec_production_index', 'united states'),
        ('n_partners_exports', 'china'),
        ('n_products_imports', 'united kingdom'),
        ('electrical_equipment_production_index', 'italy'),
        ('electrical_equipment_producer_prices', 'italy'),
        ('n_partners_imports', 'world'),
        ('n_partners_exports', 'united kingdom'),
        ('price_of_natural_gas_index', 'world'),
        ('production_index_machinery_electricals', 'italy'),
        ('price_of_copper', 'world'),
        ('electrical_equipment_production_index', 'japan'),
        ('electrical_equipment_production_index', 'world'),
        ('germany_all_products_partner_share_top_5_import_partner', 'china'),
        ('n_partners_imports', 'united kingdom'),
        ('n_partners_imports', 'china'),
        ('machinery_and_equipment_nec_production_index', 'united kingdom')
    ], 'product_group_8_sales': [
        ('electrical_equipment_production_index', 'united kingdom'),
        ('electrical_equipment_producer_prices', 'united kingdom'),
        ('n_products_imports', 'switzerland'),
        ('production_index_machinery_electricals', 'china'),
        ('production_index_machinery_electricals', 'united kingdom'),
        ('n_partners_exports', 'switzerland'),
        ('n_products_imports', 'france'),
        ('n_products_exports', 'italy'),
        ('n_partners_exports', 'france'),
        ('machinery_and_equipment_nec_production_index', 'switzerland'),
        ('n_products_exports', 'world'),
        ('germany_all_products_partner_share_top_5_export_partner', 'united states'),
        ('germany_all_products_trade_usd_mil_top_5_export_partner', 'united states'),
        ('n_partners_imports', 'switzerland'),
        ('n_products_exports', 'japan'),
        ('price_of_energy', 'world'),
        ('machinery_and_equipment_nec_production_index', 'france'),
        ('n_products_exports', 'china'),
        ('price_of_metals_minerals', 'world'),
        ('production_index_machinery_electricals', 'switzerland'),
        ('shipments_index_machinery_electricals', 'italy'),
        ('n_partners_imports', 'france'),
        ('electrical_equipment_production_index', 'france'),
        ('n_products_exports', 'united kingdom'),
        ('germany_all_products_partner_share_top_5_export_partner', 'china'),
        ('shipments_index_machinery_electricals', 'japan'),
        ('shipments_index_machinery_electricals', 'united kingdom'),
        ('price_of_crude_oil_average', 'world'),
        ('shipments_index_machinery_electricals', 'china'),
        ('production_index_machinery_electricals', 'france'),
        ('eur_in_lcu', 'united states'),
        ('price_of_base_metals', 'world'),
        ('germany_all_products_trade_usd_mil_top_5_import_partner', 'france'),
        ('production_index_machinery_electricals', 'united states'),
        ('n_products_exports', 'switzerland'),
        ('shipments_index_machinery_electricals', 'europe'),
        ('n_products_exports', 'france'),
        ('n_products_imports', 'italy'),
        ('n_products_imports', 'world'),
        ('shipments_index_machinery_electricals', 'switzerland'),
        ('n_products_imports', 'japan'),
        ('n_partners_exports', 'japan'),
        ('n_products_imports', 'china'),
        ('machinery_and_equipment_nec_production_index', 'united states'),
        ('n_partners_exports', 'china'),
        ('n_products_imports', 'united kingdom'),
        ('electrical_equipment_production_index', 'italy'),
        ('electrical_equipment_producer_prices', 'italy'),
        ('n_partners_exports', 'united kingdom'),
        ('price_of_natural_gas_index', 'world'),
        ('production_index_machinery_electricals', 'italy'),
        ('price_of_copper', 'world'),
        ('electrical_equipment_production_index', 'japan'),
        ('electrical_equipment_production_index', 'world'),
        ('n_partners_imports', 'united kingdom')
    ], 'product_group_12_sales': [
        ('electrical_equipment_production_index', 'united kingdom'),
        ('electrical_equipment_producer_prices', 'united kingdom'),
        ('n_products_imports', 'switzerland'),
        ('production_index_machinery_electricals', 'china'),
        ('production_index_machinery_electricals', 'united kingdom'),
        ('n_partners_exports', 'switzerland'),
        ('n_products_imports', 'france'),
        ('n_products_exports', 'italy'),
        ('n_products_exports', 'world'),
        ('machinery_and_equipment_nec_production_index', 'switzerland'),
        ('germany_all_products_partner_share_top_5_export_partner', 'united states'),
        ('germany_all_products_trade_usd_mil_top_5_export_partner', 'united states'),
        ('n_partners_imports', 'switzerland'),
        ('n_products_exports', 'japan'),
        ('price_of_energy', 'world'),
        ('machinery_and_equipment_nec_production_index', 'france'),
        ('n_products_exports', 'china'),
        ('price_of_metals_minerals', 'world'),
        ('production_index_machinery_electricals', 'switzerland'),
        ('shipments_index_machinery_electricals', 'italy'),
        ('n_partners_imports', 'france'),
        ('electrical_equipment_production_index', 'france'),
        ('n_products_exports', 'united kingdom'),
        ('germany_all_products_partner_share_top_5_export_partner', 'china'),
        ('shipments_index_machinery_electricals', 'japan'),
        ('germany_all_products_trade_usd_mil_top_5_export_partner', 'china'),
        ('shipments_index_machinery_electricals', 'united kingdom'),
        ('price_of_crude_oil_average', 'world'),
        ('shipments_index_machinery_electricals', 'china'),
        ('production_index_machinery_electricals', 'france'),
        ('eur_in_lcu', 'united states'),
        ('price_of_base_metals', 'world'),
        ('germany_all_products_trade_usd_mil_top_5_import_partner', 'france'),
        ('production_index_machinery_electricals', 'united states'),
        ('n_products_exports', 'switzerland'),
        ('shipments_index_machinery_electricals', 'europe'),
        ('n_products_exports', 'france'),
        ('n_products_imports', 'italy'),
        ('n_products_imports', 'world'),
        ('shipments_index_machinery_electricals', 'switzerland'),
        ('n_products_imports', 'japan'),
        ('n_products_imports', 'china'),
        ('machinery_and_equipment_nec_production_index', 'united states'),
        ('n_partners_exports', 'china'),
        ('n_products_imports', 'united kingdom'),
        ('electrical_equipment_production_index', 'italy'),
        ('electrical_equipment_producer_prices', 'italy'),
        ('n_partners_exports', 'united kingdom'),
        ('price_of_natural_gas_index', 'world'),
        ('production_index_machinery_electricals', 'italy'),
        ('price_of_copper', 'world'),
        ('electrical_equipment_production_index', 'japan'),
        ('electrical_equipment_production_index', 'world'),
        ('n_partners_imports', 'united kingdom')
    ], 'product_group_16_sales': [
        ('n_products_imports', 'switzerland'),
        ('n_products_imports', 'france'),
        ('n_products_exports', 'italy'),
        ('germany_all_products_partner_share_top_5_import_partner', 'france'),
        ('n_products_exports', 'united kingdom'),
        ('shipments_index_machinery_electricals', 'switzerland'),
        ('n_partners_exports', 'japan'),
        ('shipments_index_machinery_electricals', 'france'),
        ('n_partners_exports', 'china'),
        ('electrical_equipment_production_index', 'italy'),
        ('electrical_equipment_producer_prices', 'italy'),
        ('n_partners_imports', 'world'),
        ('production_index_machinery_electricals', 'united states'),
        ('electrical_equipment_production_index', 'united kingdom'),
        ('electrical_equipment_producer_prices', 'united kingdom'),
        ('production_index_machinery_electricals', 'japan'),
        ('production_index_machinery_electricals', 'china'),
        ('n_products_exports', 'united states'),
        ('germany_all_products_trade_usd_mil_top_5_import_partner', 'china'),
        ('germany_all_products_partner_share_top_5_export_partner', 'united states'),
        ('germany_all_products_trade_usd_mil_top_5_export_partner', 'united states'),
        ('n_products_exports', 'japan'),
        ('price_of_energy', 'world'),
        ('n_partners_imports', 'switzerland'),
        ('n_products_exports', 'china'),
        ('production_index_machinery_electricals', 'europe'),
        ('production_index_machinery_electricals', 'switzerland'),
        ('n_partners_imports', 'france'),
        ('germany_all_products_partner_share_top_5_export_partner', 'china'),
        ('germany_all_products_trade_usd_mil_top_5_export_partner', 'china'),
        ('shipments_index_machinery_electricals', 'united kingdom'),
        ('price_of_crude_oil_average', 'world'),
        ('n_products_imports', 'italy'),
        ('n_partners_exports', 'united states'),
        ('machinery_and_equipment_nec_production_index', 'united states'),
        ('electrical_equipment_producer_prices', 'united states'),
        ('n_products_imports', 'united kingdom'),
        ('electrical_equipment_production_index', 'united states'),
        ('electrical_equipment_production_index', 'japan'),
        ('machinery_and_equipment_nec_production_index', 'japan'),
        ('price_of_metals_minerals', 'world'),
        ('n_partners_imports', 'united kingdom'),
        ('electrical_equipment_producer_prices', 'china'),
        ('germany_all_products_trade_usd_mil_top_5_import_partner', 'united states'),
        ('n_partners_exports', 'switzerland'),
        ('n_partners_exports', 'france'),
        ('n_products_exports', 'world'),
        ('machinery_and_equipment_nec_production_index', 'switzerland'),
        ('machinery_and_equipment_nec_production_index', 'france'),
        ('shipments_index_machinery_electricals', 'italy'),
        ('production_index_machinery_electricals', 'france'),
        ('eur_in_lcu', 'united states'),
        ('germany_all_products_trade_usd_mil_top_5_import_partner', 'france'),
        ('n_products_exports', 'switzerland'),
        ('n_products_imports', 'united states'),
        ('n_products_exports', 'france'),
        ('germany_all_products_partner_share_top_5_export_partner', 'france'),
        ('n_products_imports', 'japan'),
        ('germany_all_products_trade_usd_mil_top_5_export_partner', 'france'),
        ('germany_all_products_partner_share_top_5_import_partner', 'united states'),
        ('n_partners_exports', 'world'),
        ('n_products_imports', 'china'),
        ('n_partners_imports', 'italy'),
        ('machinery_and_equipment_nec_production_index', 'world'),
        ('production_index_machinery_electricals', 'italy'),
        ('germany_all_products_partner_share_top_5_import_partner', 'china'),
        ('production_index_machinery_electricals', 'united kingdom'),
        ('is_recession', 'world'),
        ('electrical_equipment_production_index', 'switzerland'),
        ('shipments_index_machinery_electricals', 'united states'),
        ('electrical_equipment_production_index', 'france'),
        ('electrical_equipment_producer_prices', 'france'),
        ('shipments_index_machinery_electricals', 'japan'),
        ('shipments_index_machinery_electricals', 'china'),
        ('price_of_base_metals', 'world'),
        ('shipments_index_machinery_electricals', 'europe'),
        ('n_products_imports', 'world'),
        ('n_partners_exports', 'italy'),
        ('machinery_and_equipment_nec_production_index', 'italy'),
        ('n_partners_imports', 'united states'),
        ('n_partners_exports', 'united kingdom'),
        ('price_of_natural_gas_index', 'world'),
        ('n_partners_imports', 'japan'),
        ('price_of_copper', 'world'),
        ('electrical_equipment_production_index', 'world'),
        ('n_partners_imports', 'china'),
        ('machinery_and_equipment_nec_production_index', 'united kingdom')
    ], 'product_group_4_sales': [
        ('electrical_equipment_production_index', 'united kingdom'),
        ('electrical_equipment_producer_prices', 'united kingdom'),
        ('n_products_imports', 'switzerland'),
        ('production_index_machinery_electricals', 'china'),
        ('production_index_machinery_electricals', 'united kingdom'),
        ('n_partners_exports', 'switzerland'),
        ('n_products_imports', 'france'),
        ('n_products_exports', 'italy'),
        ('n_partners_exports', 'france'),
        ('machinery_and_equipment_nec_production_index', 'switzerland'),
        ('n_products_exports', 'world'),
        ('germany_all_products_partner_share_top_5_export_partner', 'united states'),
        ('germany_all_products_trade_usd_mil_top_5_export_partner', 'united states'),
        ('n_partners_imports', 'switzerland'),
        ('n_products_exports', 'japan'),
        ('price_of_energy', 'world'),
        ('machinery_and_equipment_nec_production_index', 'france'),
        ('n_products_exports', 'china'),
        ('price_of_metals_minerals', 'world'),
        ('production_index_machinery_electricals', 'switzerland'),
        ('shipments_index_machinery_electricals', 'italy'),
        ('n_partners_imports', 'france'),
        ('electrical_equipment_production_index', 'france'),
        ('n_products_exports', 'united kingdom'),
        ('germany_all_products_partner_share_top_5_export_partner', 'china'),
        ('shipments_index_machinery_electricals', 'japan'),
        ('germany_all_products_trade_usd_mil_top_5_export_partner', 'china'),
        ('shipments_index_machinery_electricals', 'united kingdom'),
        ('shipments_index_machinery_electricals', 'china'),
        ('production_index_machinery_electricals', 'france'),
        ('eur_in_lcu', 'united states'),
        ('price_of_base_metals', 'world'),
        ('germany_all_products_trade_usd_mil_top_5_import_partner', 'france'),
        ('production_index_machinery_electricals', 'united states'),
        ('n_products_exports', 'switzerland'),
        ('shipments_index_machinery_electricals', 'europe'),
        ('n_products_exports', 'france'),
        ('n_products_imports', 'italy'),
        ('n_products_imports', 'world'),
        ('shipments_index_machinery_electricals', 'switzerland'),
        ('n_products_imports', 'japan'),
        ('n_partners_exports', 'japan'),
        ('n_partners_exports', 'world'),
        ('n_products_imports', 'china'),
        ('machinery_and_equipment_nec_production_index', 'united states'),
        ('n_partners_exports', 'china'),
        ('n_products_imports', 'united kingdom'),
        ('electrical_equipment_production_index', 'italy'),
        ('electrical_equipment_producer_prices', 'italy'),
        ('n_partners_exports', 'united kingdom'),
        ('price_of_natural_gas_index', 'world'),
        ('production_index_machinery_electricals', 'italy'),
        ('price_of_copper', 'world'),
        ('electrical_equipment_production_index', 'japan'),
        ('electrical_equipment_production_index', 'world'),
        ('n_partners_imports', 'united kingdom'),
        ('n_partners_imports', 'china')
    ], 'product_group_5_sales': [
        ('electrical_equipment_production_index', 'united kingdom'),
        ('electrical_equipment_producer_prices', 'united kingdom'),
        ('n_products_imports', 'switzerland'),
        ('production_index_machinery_electricals', 'china'),
        ('production_index_machinery_electricals', 'united kingdom'),
        ('n_partners_exports', 'switzerland'),
        ('n_products_imports', 'france'),
        ('n_products_exports', 'italy'),
        ('n_partners_exports', 'france'),
        ('machinery_and_equipment_nec_production_index', 'switzerland'),
        ('n_products_exports', 'world'),
        ('germany_all_products_partner_share_top_5_export_partner', 'united states'),
        ('germany_all_products_trade_usd_mil_top_5_export_partner', 'united states'),
        ('n_partners_imports', 'switzerland'),
        ('n_products_exports', 'japan'),
        ('price_of_energy', 'world'),
        ('machinery_and_equipment_nec_production_index', 'france'),
        ('n_products_exports', 'china'),
        ('price_of_metals_minerals', 'world'),
        ('production_index_machinery_electricals', 'switzerland'),
        ('shipments_index_machinery_electricals', 'italy'),
        ('n_partners_imports', 'france'),
        ('electrical_equipment_production_index', 'france'),
        ('n_products_exports', 'united kingdom'),
        ('germany_all_products_partner_share_top_5_export_partner', 'china'),
        ('shipments_index_machinery_electricals', 'japan'),
        ('germany_all_products_trade_usd_mil_top_5_export_partner', 'china'),
        ('shipments_index_machinery_electricals', 'united kingdom'),
        ('price_of_crude_oil_average', 'world'),
        ('shipments_index_machinery_electricals', 'china'),
        ('production_index_machinery_electricals', 'france'),
        ('eur_in_lcu', 'united states'),
        ('price_of_base_metals', 'world'),
        ('germany_all_products_trade_usd_mil_top_5_import_partner', 'france'),
        ('production_index_machinery_electricals', 'united states'),
        ('n_products_exports', 'switzerland'),
        ('shipments_index_machinery_electricals', 'europe'),
        ('n_products_exports', 'france'),
        ('n_products_imports', 'italy'),
        ('n_products_imports', 'world'),
        ('n_partners_exports', 'italy'),
        ('shipments_index_machinery_electricals', 'switzerland'),
        ('n_products_imports', 'japan'),
        ('n_partners_exports', 'japan'),
        ('n_partners_exports', 'world'),
        ('n_products_imports', 'china'),
        ('machinery_and_equipment_nec_production_index', 'united states'),
        ('n_partners_exports', 'china'),
        ('n_products_imports', 'united kingdom'),
        ('electrical_equipment_production_index', 'italy'),
        ('electrical_equipment_producer_prices', 'italy'),
        ('n_partners_exports', 'united kingdom'),
        ('price_of_natural_gas_index', 'world'),
        ('production_index_machinery_electricals', 'italy'),
        ('price_of_copper', 'world'),
        ('electrical_equipment_production_index', 'japan'),
        ('electrical_equipment_production_index', 'world'),
        ('n_partners_imports', 'united kingdom'),
        ('n_partners_imports', 'china')
    ], 'product_group_3_sales': [
        ('electrical_equipment_production_index', 'united kingdom'),
        ('electrical_equipment_producer_prices', 'united kingdom'),
        ('n_products_imports', 'switzerland'),
        ('production_index_machinery_electricals', 'china'),
        ('production_index_machinery_electricals', 'united kingdom'),
        ('n_partners_exports', 'switzerland'),
        ('n_products_imports', 'france'),
        ('n_products_exports', 'italy'),
        ('n_partners_exports', 'france'),
        ('machinery_and_equipment_nec_production_index', 'switzerland'),
        ('n_products_exports', 'world'),
        ('germany_all_products_partner_share_top_5_export_partner', 'united states'),
        ('germany_all_products_trade_usd_mil_top_5_export_partner', 'united states'),
        ('n_partners_imports', 'switzerland'),
        ('n_products_exports', 'japan'),
        ('price_of_energy', 'world'),
        ('machinery_and_equipment_nec_production_index', 'france'),
        ('n_products_exports', 'china'),
        ('price_of_metals_minerals', 'world'),
        ('production_index_machinery_electricals', 'switzerland'),
        ('shipments_index_machinery_electricals', 'italy'),
        ('n_partners_imports', 'france'),
        ('electrical_equipment_production_index', 'france'),
        ('n_products_exports', 'united kingdom'),
        ('germany_all_products_partner_share_top_5_export_partner', 'china'),
        ('shipments_index_machinery_electricals', 'japan'),
        ('germany_all_products_trade_usd_mil_top_5_export_partner', 'china'),
        ('shipments_index_machinery_electricals', 'united kingdom'),
        ('price_of_crude_oil_average', 'world'),
        ('shipments_index_machinery_electricals', 'china'),
        ('production_index_machinery_electricals', 'france'),
        ('eur_in_lcu', 'united states'),
        ('price_of_base_metals', 'world'),
        ('germany_all_products_trade_usd_mil_top_5_import_partner', 'france'),
        ('production_index_machinery_electricals', 'united states'),
        ('n_products_exports', 'switzerland'),
        ('shipments_index_machinery_electricals', 'europe'),
        ('n_products_exports', 'france'),
        ('n_products_imports', 'italy'),
        ('n_products_imports', 'world'),
        ('shipments_index_machinery_electricals', 'switzerland'),
        ('n_products_imports', 'japan'),
        ('n_partners_exports', 'japan'),
        ('n_partners_exports', 'world'),
        ('n_products_imports', 'china'),
        ('machinery_and_equipment_nec_production_index', 'united states'),
        ('n_partners_exports', 'china'),
        ('n_products_imports', 'united kingdom'),
        ('electrical_equipment_production_index', 'italy'),
        ('electrical_equipment_producer_prices', 'italy'),
        ('n_partners_imports', 'world'),
        ('n_partners_exports', 'united kingdom'),
        ('price_of_natural_gas_index', 'world'),
        ('production_index_machinery_electricals', 'italy'),
        ('price_of_copper', 'world'),
        ('electrical_equipment_production_index', 'japan'),
        ('electrical_equipment_production_index', 'world'),
        ('n_partners_imports', 'united kingdom'),
        ('n_partners_imports', 'china')
    ], 'product_group_9_sales': [
        ('electrical_equipment_production_index', 'united kingdom'),
        ('electrical_equipment_producer_prices', 'united kingdom'),
        ('n_products_imports', 'switzerland'),
        ('production_index_machinery_electricals', 'china'),
        ('production_index_machinery_electricals', 'united kingdom'),
        ('n_partners_exports', 'switzerland'),
        ('n_products_imports', 'france'),
        ('n_products_exports', 'italy'),
        ('n_products_exports', 'world'),
        ('machinery_and_equipment_nec_production_index', 'switzerland'),
        ('germany_all_products_partner_share_top_5_export_partner', 'united states'),
        ('germany_all_products_trade_usd_mil_top_5_export_partner', 'united states'),
        ('n_products_exports', 'japan'),
        ('price_of_energy', 'world'),
        ('machinery_and_equipment_nec_production_index', 'france'),
        ('n_products_exports', 'china'),
        ('price_of_metals_minerals', 'world'),
        ('production_index_machinery_electricals', 'switzerland'),
        ('shipments_index_machinery_electricals', 'italy'),
        ('electrical_equipment_production_index', 'france'),
        ('n_products_exports', 'united kingdom'),
        ('germany_all_products_partner_share_top_5_export_partner', 'china'),
        ('shipments_index_machinery_electricals', 'japan'),
        ('germany_all_products_trade_usd_mil_top_5_export_partner', 'china'),
        ('shipments_index_machinery_electricals', 'united kingdom'),
        ('price_of_crude_oil_average', 'world'),
        ('shipments_index_machinery_electricals', 'china'),
        ('production_index_machinery_electricals', 'france'),
        ('eur_in_lcu', 'united states'),
        ('price_of_base_metals', 'world'),
        ('germany_all_products_trade_usd_mil_top_5_import_partner', 'france'),
        ('production_index_machinery_electricals', 'united states'),
        ('n_products_exports', 'switzerland'),
        ('shipments_index_machinery_electricals', 'europe'),
        ('n_products_exports', 'france'),
        ('n_products_imports', 'italy'),
        ('n_products_imports', 'world'),
        ('n_partners_exports', 'italy'),
        ('shipments_index_machinery_electricals', 'switzerland'),
        ('n_partners_exports', 'united states'),
        ('n_products_imports', 'japan'),
        ('n_partners_exports', 'world'),
        ('n_products_imports', 'china'),
        ('machinery_and_equipment_nec_production_index', 'united states'),
        ('n_partners_exports', 'china'),
        ('n_products_imports', 'united kingdom'),
        ('electrical_equipment_production_index', 'italy'),
        ('electrical_equipment_producer_prices', 'italy'),
        ('n_partners_imports', 'world'),
        ('n_partners_exports', 'united kingdom'),
        ('price_of_natural_gas_index', 'world'),
        ('production_index_machinery_electricals', 'italy'),
        ('n_partners_imports', 'japan'),
        ('price_of_copper', 'world'),
        ('electrical_equipment_production_index', 'japan'),
        ('electrical_equipment_production_index', 'world'),
        ('n_partners_imports', 'united kingdom'),
        ('n_partners_imports', 'china')
    ], 'product_group_14_sales': [
        ('electrical_equipment_production_index', 'united kingdom'),
        ('electrical_equipment_producer_prices', 'united kingdom'),
        ('n_products_imports', 'switzerland'),
        ('production_index_machinery_electricals', 'china'),
        ('production_index_machinery_electricals', 'united kingdom'),
        ('n_partners_exports', 'switzerland'),
        ('n_products_imports', 'france'),
        ('n_products_exports', 'italy'),
        ('n_products_exports', 'world'),
        ('germany_all_products_partner_share_top_5_export_partner', 'united states'),
        ('germany_all_products_trade_usd_mil_top_5_export_partner', 'united states'),
        ('n_products_exports', 'japan'),
        ('price_of_energy', 'world'),
        ('machinery_and_equipment_nec_production_index', 'france'),
        ('n_products_exports', 'china'),
        ('price_of_metals_minerals', 'world'),
        ('production_index_machinery_electricals', 'switzerland'),
        ('shipments_index_machinery_electricals', 'italy'),
        ('electrical_equipment_production_index', 'france'),
        ('n_products_exports', 'united kingdom'),
        ('germany_all_products_partner_share_top_5_export_partner', 'china'),
        ('shipments_index_machinery_electricals', 'japan'),
        ('germany_all_products_trade_usd_mil_top_5_export_partner', 'china'),
        ('shipments_index_machinery_electricals', 'united kingdom'),
        ('price_of_crude_oil_average', 'world'),
        ('shipments_index_machinery_electricals', 'china'),
        ('production_index_machinery_electricals', 'france'),
        ('eur_in_lcu', 'united states'),
        ('price_of_base_metals', 'world'),
        ('production_index_machinery_electricals', 'united states'),
        ('n_products_exports', 'switzerland'),
        ('shipments_index_machinery_electricals', 'europe'),
        ('n_products_exports', 'france'),
        ('n_products_imports', 'italy'),
        ('n_products_imports', 'world'),
        ('shipments_index_machinery_electricals', 'switzerland'),
        ('n_partners_exports', 'united states'),
        ('n_products_imports', 'japan'),
        ('n_partners_exports', 'world'),
        ('n_products_imports', 'china'),
        ('machinery_and_equipment_nec_production_index', 'united states'),
        ('n_partners_exports', 'china'),
        ('n_products_imports', 'united kingdom'),
        ('electrical_equipment_production_index', 'italy'),
        ('electrical_equipment_producer_prices', 'italy'),
        ('n_partners_exports', 'united kingdom'),
        ('price_of_natural_gas_index', 'world'),
        ('production_index_machinery_electricals', 'italy'),
        ('n_partners_imports', 'japan'),
        ('price_of_copper', 'world'),
        ('electrical_equipment_production_index', 'japan'),
        ('electrical_equipment_production_index', 'world'),
        ('n_partners_imports', 'united kingdom'),
        ('n_partners_imports', 'china')
    ], 'product_group_13_sales': [
        ('electrical_equipment_production_index', 'united kingdom'),
        ('electrical_equipment_producer_prices', 'united kingdom'),
        ('n_products_imports', 'switzerland'),
        ('production_index_machinery_electricals', 'china'),
        ('production_index_machinery_electricals', 'united kingdom'),
        ('n_partners_exports', 'switzerland'),
        ('n_products_imports', 'france'),
        ('n_products_exports', 'italy'),
        ('n_partners_exports', 'france'),
        ('n_products_exports', 'world'),
        ('germany_all_products_trade_usd_mil_top_5_import_partner', 'china'),
        ('germany_all_products_partner_share_top_5_export_partner', 'united states'),
        ('germany_all_products_trade_usd_mil_top_5_export_partner', 'united states'),
        ('n_partners_imports', 'switzerland'),
        ('n_products_exports', 'japan'),
        ('price_of_energy', 'world'),
        ('germany_all_products_partner_share_top_5_import_partner', 'france'),
        ('machinery_and_equipment_nec_production_index', 'france'),
        ('n_products_exports', 'china'),
        ('price_of_metals_minerals', 'world'),
        ('production_index_machinery_electricals', 'switzerland'),
        ('n_partners_imports', 'france'),
        ('shipments_index_machinery_electricals', 'italy'),
        ('electrical_equipment_production_index', 'france'),
        ('n_products_exports', 'united kingdom'),
        ('germany_all_products_partner_share_top_5_export_partner', 'china'),
        ('shipments_index_machinery_electricals', 'japan'),
        ('germany_all_products_trade_usd_mil_top_5_export_partner', 'china'),
        ('shipments_index_machinery_electricals', 'united kingdom'),
        ('price_of_crude_oil_average', 'world'),
        ('shipments_index_machinery_electricals', 'china'),
        ('production_index_machinery_electricals', 'france'),
        ('eur_in_lcu', 'united states'),
        ('price_of_base_metals', 'world'),
        ('germany_all_products_trade_usd_mil_top_5_import_partner', 'france'),
        ('production_index_machinery_electricals', 'united states'),
        ('n_products_exports', 'switzerland'),
        ('shipments_index_machinery_electricals', 'europe'),
        ('n_products_exports', 'france'),
        ('n_products_imports', 'italy'),
        ('n_products_imports', 'world'),
        ('n_partners_exports', 'italy'),
        ('shipments_index_machinery_electricals', 'switzerland'),
        ('n_products_imports', 'japan'),
        ('n_partners_exports', 'japan'),
        ('n_partners_exports', 'world'),
        ('n_products_imports', 'china'),
        ('machinery_and_equipment_nec_production_index', 'united states'),
        ('n_partners_exports', 'china'),
        ('n_products_imports', 'united kingdom'),
        ('electrical_equipment_production_index', 'italy'),
        ('electrical_equipment_producer_prices', 'italy'),
        ('n_partners_exports', 'united kingdom'),
        ('price_of_natural_gas_index', 'world'),
        ('production_index_machinery_electricals', 'italy'),
        ('price_of_copper', 'world'),
        ('electrical_equipment_production_index', 'japan'),
        ('electrical_equipment_production_index', 'world'),
        ('germany_all_products_partner_share_top_5_import_partner', 'china'),
        ('n_partners_imports', 'united kingdom')
    ], 'product_group_20_sales': [
        ('electrical_equipment_producer_prices', 'united kingdom'),
        ('n_products_imports', 'switzerland'),
        ('production_index_machinery_electricals', 'china'),
        ('production_index_machinery_electricals', 'united kingdom'),
        ('n_products_imports', 'france'),
        ('n_products_exports', 'italy'),
        ('n_products_exports', 'world'),
        ('machinery_and_equipment_nec_production_index', 'switzerland'),
        ('germany_all_products_trade_usd_mil_top_5_import_partner', 'china'),
        ('germany_all_products_partner_share_top_5_export_partner', 'united states'),
        ('germany_all_products_trade_usd_mil_top_5_export_partner', 'united states'),
        ('n_products_exports', 'japan'),
        ('price_of_energy', 'world'),
        ('germany_all_products_partner_share_top_5_import_partner', 'france'),
        ('machinery_and_equipment_nec_production_index', 'france'),
        ('n_products_exports', 'china'),
        ('price_of_metals_minerals', 'world'),
        ('production_index_machinery_electricals', 'switzerland'),
        ('shipments_index_machinery_electricals', 'italy'),
        ('electrical_equipment_production_index', 'france'),
        ('n_products_exports', 'united kingdom'),
        ('germany_all_products_partner_share_top_5_export_partner', 'china'),
        ('shipments_index_machinery_electricals', 'japan'),
        ('germany_all_products_trade_usd_mil_top_5_export_partner', 'china'),
        ('shipments_index_machinery_electricals', 'united kingdom'),
        ('price_of_crude_oil_average', 'world'),
        ('shipments_index_machinery_electricals', 'china'),
        ('production_index_machinery_electricals', 'france'),
        ('eur_in_lcu', 'united states'),
        ('price_of_base_metals', 'world'),
        ('germany_all_products_trade_usd_mil_top_5_import_partner', 'france'),
        ('production_index_machinery_electricals', 'united states'),
        ('n_products_exports', 'switzerland'),
        ('shipments_index_machinery_electricals', 'europe'),
        ('n_products_exports', 'france'),
        ('n_products_imports', 'italy'),
        ('n_products_imports', 'world'),
        ('n_partners_exports', 'italy'),
        ('shipments_index_machinery_electricals', 'switzerland'),
        ('n_partners_exports', 'united states'),
        ('n_products_imports', 'japan'),
        ('n_partners_exports', 'japan'),
        ('n_partners_exports', 'world'),
        ('n_products_imports', 'china'),
        ('machinery_and_equipment_nec_production_index', 'united states'),
        ('n_partners_exports', 'china'),
        ('n_products_imports', 'united kingdom'),
        ('electrical_equipment_production_index', 'italy'),
        ('electrical_equipment_producer_prices', 'italy'),
        ('n_partners_imports', 'world'),
        ('n_partners_exports', 'united kingdom'),
        ('price_of_natural_gas_index', 'world'),
        ('production_index_machinery_electricals', 'italy'),
        ('n_partners_imports', 'japan'),
        ('price_of_copper', 'world'),
        ('electrical_equipment_production_index', 'japan'),
        ('germany_all_products_partner_share_top_5_import_partner', 'china'),
        ('n_partners_imports', 'united kingdom'),
        ('n_partners_imports', 'china')
    ], 'product_group_36_sales': [
        ('n_products_imports', 'switzerland'),
        ('n_products_imports', 'france'),
        ('n_products_exports', 'italy'),
        ('germany_all_products_partner_share_top_5_import_partner', 'france'),
        ('n_products_exports', 'united kingdom'),
        ('shipments_index_machinery_electricals', 'switzerland'),
        ('n_partners_exports', 'japan'),
        ('shipments_index_machinery_electricals', 'france'),
        ('n_partners_exports', 'china'),
        ('electrical_equipment_production_index', 'italy'),
        ('electrical_equipment_producer_prices', 'italy'),
        ('n_partners_imports', 'world'),
        ('production_index_machinery_electricals', 'united states'),
        ('electrical_equipment_production_index', 'united kingdom'),
        ('electrical_equipment_producer_prices', 'united kingdom'),
        ('production_index_machinery_electricals', 'japan'),
        ('production_index_machinery_electricals', 'china'),
        ('n_products_exports', 'united states'),
        ('germany_all_products_trade_usd_mil_top_5_import_partner', 'china'),
        ('germany_all_products_partner_share_top_5_export_partner', 'united states'),
        ('germany_all_products_trade_usd_mil_top_5_export_partner', 'united states'),
        ('n_products_exports', 'japan'),
        ('price_of_energy', 'world'),
        ('n_partners_imports', 'switzerland'),
        ('n_products_exports', 'china'),
        ('production_index_machinery_electricals', 'europe'),
        ('production_index_machinery_electricals', 'switzerland'),
        ('n_partners_imports', 'france'),
        ('germany_all_products_partner_share_top_5_export_partner', 'china'),
        ('germany_all_products_trade_usd_mil_top_5_export_partner', 'china'),
        ('shipments_index_machinery_electricals', 'united kingdom'),
        ('price_of_crude_oil_average', 'world'),
        ('n_products_imports', 'italy'),
        ('n_partners_exports', 'united states'),
        ('machinery_and_equipment_nec_production_index', 'united states'),
        ('electrical_equipment_producer_prices', 'united states'),
        ('n_products_imports', 'united kingdom'),
        ('electrical_equipment_production_index', 'united states'),
        ('electrical_equipment_production_index', 'japan'),
        ('machinery_and_equipment_nec_production_index', 'japan'),
        ('price_of_metals_minerals', 'world'),
        ('n_partners_imports', 'united kingdom'),
        ('electrical_equipment_producer_prices', 'china'),
        ('germany_all_products_trade_usd_mil_top_5_import_partner', 'united states'),
        ('n_partners_exports', 'switzerland'),
        ('n_products_exports', 'world'),
        ('machinery_and_equipment_nec_production_index', 'switzerland'),
        ('n_partners_exports', 'france'),
        ('machinery_and_equipment_nec_production_index', 'france'),
        ('shipments_index_machinery_electricals', 'italy'),
        ('production_index_machinery_electricals', 'france'),
        ('eur_in_lcu', 'united states'),
        ('germany_all_products_trade_usd_mil_top_5_import_partner', 'france'),
        ('n_products_exports', 'switzerland'),
        ('n_products_imports', 'united states'),
        ('n_products_exports', 'france'),
        ('germany_all_products_partner_share_top_5_export_partner', 'france'),
        ('n_products_imports', 'japan'),
        ('germany_all_products_trade_usd_mil_top_5_export_partner', 'france'),
        ('germany_all_products_partner_share_top_5_import_partner', 'united states'),
        ('n_partners_exports', 'world'),
        ('n_products_imports', 'china'),
        ('n_partners_imports', 'italy'),
        ('machinery_and_equipment_nec_production_index', 'world'),
        ('production_index_machinery_electricals', 'italy'),
        ('germany_all_products_partner_share_top_5_import_partner', 'china'),
        ('production_index_machinery_electricals', 'united kingdom'),
        ('is_recession', 'world'),
        ('electrical_equipment_production_index', 'switzerland'),
        ('shipments_index_machinery_electricals', 'united states'),
        ('electrical_equipment_production_index', 'france'),
        ('electrical_equipment_producer_prices', 'france'),
        ('shipments_index_machinery_electricals', 'japan'),
        ('shipments_index_machinery_electricals', 'china'),
        ('price_of_base_metals', 'world'),
        ('shipments_index_machinery_electricals', 'europe'),
        ('n_products_imports', 'world'),
        ('n_partners_exports', 'italy'),
        ('machinery_and_equipment_nec_production_index', 'italy'),
        ('n_partners_imports', 'united states'),
        ('n_partners_exports', 'united kingdom'),
        ('price_of_natural_gas_index', 'world'),
        ('n_partners_imports', 'japan'),
        ('price_of_copper', 'world'),
        ('electrical_equipment_production_index', 'world'),
        ('n_partners_imports', 'china'),
        ('machinery_and_equipment_nec_production_index', 'united kingdom')
    ]
}

BEST_FEATURES = [
    ('japan', 'shipments_index_machinery_electricals'),
    ('germany', 'product_group_36_sales'),
    ('china', 'germany_all_products_trade_usd_mil_top_5_import_partner'),
    ('united states', 'n_partners_imports'),
    ('france', 'germany_all_products_partner_share_top_5_import_partner'),
    ('japan', 'n_products_imports'),
    ('united states', 'n_partners_exports'),
    ('germany', 'product_group_14_sales'),
    ('germany', 'product_group_9_sales'),
    ('europe', 'shipments_index_machinery_electricals'),
    ('germany', 'product_group_12_sales'),
    ('united kingdom', 'machinery_and_equipment_nec_production_index'),
    ('france', 'shipments_index_machinery_electricals'),
    ('germany', 'product_group_6_sales'),
    ('china', 'n_partners_exports'),
    ('china', 'n_partners_imports'),
    ('switzerland', 'n_products_imports'),
    ('united kingdom', 'electrical_equipment_producer_prices'),
    ('italy', 'n_partners_exports'),
    ('united states', 'production_index_machinery_electricals'),
    ('italy', 'n_partners_imports'),
    ('germany', 'product_group_16_sales'),
    ('germany', 'product_group_13_sales'),
    ('united kingdom', 'electrical_equipment_production_index'),
    ('china', 'germany_all_products_partner_share_top_5_import_partner'),
    ('united kingdom', 'n_partners_exports'),
    ('world', 'machinery_and_equipment_nec_production_index'),
    ('united kingdom', 'n_partners_imports'),
    ('germany', 'product_group_20_sales'),
    ('germany', 'product_group_4_sales'),
    ('japan', 'n_partners_exports'),
    ('china', 'production_index_machinery_electricals'),
    ('japan', 'n_partners_imports'),
    ('china', 'shipments_index_machinery_electricals'),
    ('world', 'is_recession'),
    ('united states', 'machinery_and_equipment_nec_production_index'),
    ('switzerland', 'electrical_equipment_production_index'),
    ('italy', 'shipments_index_machinery_electricals'),
    ('world', 'electrical_equipment_production_index'),
    ('switzerland', 'n_partners_imports'),
    ('germany', 'product_group_1_sales'),
    ('france', 'n_partners_exports'),
    ('italy', 'n_products_imports'),
    ('switzerland', 'n_partners_exports'),
    ('france', 'n_partners_imports'),
    ('germany', 'product_group_5_sales'),
    ('united kingdom', 'production_index_machinery_electricals'),
    ('world', 'n_partners_exports'),
    ('world', 'n_partners_imports')
 ]

SALES_K_BEST_FEATURES = {
    'product_group_1_sales': [
        ('china', 'germany_all_products_partner_share_top_5_import_partner'),
        ('china', 'germany_all_products_trade_usd_mil_top_5_import_partner'),
        ('france', 'germany_all_products_partner_share_top_5_import_partner'),
        ('germany', 'china_all_products_trade_usd_mil_top_5_import_partner'),
        ('germany', 'log_product_group_3_sales'),
        ('germany', 'log_product_group_4_sales'),
        ('germany', 'log_product_group_5_sales'),
        ('germany', 'log_product_group_6_sales'),
        ('germany', 'product_group_1_sales'),
        ('germany', 'united_kingdom_all_products_trade_usd_mil_top_5_import_partner'),
        ('germany', 'world_all_products_exports_in_usd_mil'),
        ('germany', 'world_capital_goods_export_usd_mil'),
        ('germany', 'world_consumer_goods_export_product_share'),
        ('germany', 'world_consumer_goods_export_usd_mil'),
        ('germany', 'world_consumer_goods_import_product_share'),
        ('germany', 'world_consumer_goods_import_usd_mil'),
        ('germany', 'world_intermediate_goods_export_product_share'),
        ('germany', 'world_raw_materials_export_usd_mil'),
        ('germany', 'world_transportation_export_usd_mil'),
        ('world', 'electrical_equipment_production_index')
    ], 'product_group_11_sales': [
        ('china', 'germany_all_products_partner_share_top_5_import_partner'),
        ('china', 'germany_all_products_trade_usd_mil_top_5_import_partner'),
        ('france', 'germany_all_products_partner_share_top_5_import_partner'),
        ('germany', 'log_product_group_11_sales'),
        ('germany', 'log_product_group_3_sales'),
        ('germany', 'log_product_group_4_sales'),
        ('germany', 'log_product_group_5_sales'),
        ('germany', 'log_product_group_6_sales'),
        ('germany', 'n_products_imports'),
        ('germany', 'united_kingdom_all_products_trade_usd_mil_top_5_import_partner'),
        ('germany', 'world_all_products_exports_in_usd_mil'),
        ('germany', 'world_capital_goods_export_usd_mil'),
        ('germany', 'world_consumer_goods_export_product_share'),
        ('germany', 'world_consumer_goods_export_usd_mil'),
        ('germany', 'world_consumer_goods_import_product_share'),
        ('germany', 'world_consumer_goods_import_usd_mil'),
        ('germany', 'world_intermediate_goods_export_product_share'),
        ('germany', 'world_raw_materials_export_usd_mil'),
        ('germany', 'world_transportation_export_usd_mil'),
        ('world', 'electrical_equipment_production_index')
    ], 'product_group_6_sales': [
        ('china', 'germany_all_products_partner_share_top_5_import_partner'),
        ('china', 'germany_all_products_trade_usd_mil_top_5_import_partner'),
        ('france', 'germany_all_products_partner_share_top_5_import_partner'),
        ('germany', 'china_all_products_trade_usd_mil_top_5_import_partner'),
        ('germany', 'log_product_group_4_sales'),
        ('germany', 'log_product_group_6_sales'),
        ('germany', 'n_products_imports'),
        ('germany', 'product_group_6_sales'),
        ('germany', 'united_kingdom_all_products_trade_usd_mil_top_5_import_partner'),
        ('germany', 'world_all_products_exports_in_usd_mil'),
        ('germany', 'world_capital_goods_export_usd_mil'),
        ('germany', 'world_consumer_goods_export_product_share'),
        ('germany', 'world_consumer_goods_export_usd_mil'),
        ('germany', 'world_consumer_goods_import_product_share'),
        ('germany', 'world_consumer_goods_import_usd_mil'),
        ('germany', 'world_intermediate_goods_export_product_share'),
        ('germany', 'world_raw_materials_export_usd_mil'),
        ('germany', 'world_transportation_export_usd_mil'),
        ('united states', 'n_products_exports'),
        ('world', 'electrical_equipment_production_index')
    ], 'product_group_8_sales': [
        ('china', 'production_index_machinery_electricals'),
        ('china', 'shipments_index_machinery_electricals'),
        ('france', 'germany_all_products_partner_share_top_5_import_partner'),
        ('germany', 'log_product_group_11_sales'),
        ('germany', 'log_product_group_12_sales'),
        ('germany', 'log_product_group_13_sales'),
        ('germany', 'log_product_group_16_sales'),
        ('germany', 'log_product_group_1_sales'),
        ('germany', 'log_product_group_3_sales'),
        ('germany', 'log_product_group_4_sales'),
        ('germany', 'log_product_group_5_sales'),
        ('germany', 'log_product_group_6_sales'),
        ('germany', 'log_product_group_8_sales'),
        ('germany', 'n_products_imports'),
        ('germany', 'world_consumer_goods_export_product_share'),
        ('germany', 'world_consumer_goods_import_product_share'),
        ('germany', 'world_intermediate_goods_export_product_share'),
        ('italy', 'n_partners_exports'),
        ('japan', 'n_products_imports'),
        ('world', 'electrical_equipment_production_index')
    ], 'product_group_12_sales': [
        ('china', 'germany_all_products_partner_share_top_5_import_partner'),
        ('china', 'germany_all_products_trade_usd_mil_top_5_import_partner'),
        ('china', 'production_index_machinery_electricals'),
        ('china', 'shipments_index_machinery_electricals'),
        ('france', 'germany_all_products_partner_share_top_5_import_partner'),
        ('germany', 'log_product_group_11_sales'),
        ('germany', 'log_product_group_12_sales'),
        ('germany', 'log_product_group_13_sales'),
        ('germany', 'log_product_group_1_sales'),
        ('germany', 'log_product_group_3_sales'),
        ('germany', 'log_product_group_4_sales'),
        ('germany', 'log_product_group_5_sales'),
        ('germany', 'log_product_group_6_sales'),
        ('germany', 'log_product_group_8_sales'),
        ('germany', 'product_group_12_sales'),
        ('germany', 'united_kingdom_all_products_trade_usd_mil_top_5_import_partner'),
        ('germany', 'world_intermediate_goods_export_product_share'),
        ('switzerland', 'electrical_equipment_production_index'),
        ('united kingdom', 'machinery_and_equipment_nec_production_index'),
        ('world', 'electrical_equipment_production_index')
    ], 'product_group_16_sales': [
        ('china', 'germany_all_products_partner_share_top_5_import_partner'),
        ('china', 'germany_all_products_trade_usd_mil_top_5_import_partner'),
        ('germany', 'china_all_products_trade_usd_mil_top_5_import_partner'),
        ('germany', 'log_product_group_11_sales'),
        ('germany', 'log_product_group_13_sales'),
        ('germany', 'log_product_group_1_sales'),
        ('germany', 'log_product_group_3_sales'),
        ('germany', 'log_product_group_4_sales'),
        ('germany', 'log_product_group_5_sales'),
        ('germany', 'product_group_16_sales'),
        ('germany', 'united_kingdom_all_products_trade_usd_mil_top_5_import_partner'),
        ('germany', 'world_all_products_exports_in_usd_mil'),
        ('germany', 'world_capital_goods_export_usd_mil'),
        ('germany', 'world_consumer_goods_export_usd_mil'),
        ('germany', 'world_consumer_goods_import_usd_mil'),
        ('germany', 'world_intermediate_goods_export_product_share'),
        ('germany', 'world_raw_materials_export_usd_mil'),
        ('germany', 'world_transportation_export_usd_mil'),
        ('united states', 'n_products_exports'),
        ('world', 'electrical_equipment_production_index')
    ], 'product_group_4_sales': [
        ('china', 'germany_all_products_partner_share_top_5_import_partner'),
        ('china', 'germany_all_products_trade_usd_mil_top_5_import_partner'),
        ('germany', 'china_all_products_trade_usd_mil_top_5_import_partner'),
        ('germany', 'log_product_group_11_sales'),
        ('germany', 'log_product_group_16_sales'),
        ('germany', 'log_product_group_1_sales'),
        ('germany', 'log_product_group_3_sales'),
        ('germany', 'log_product_group_4_sales'),
        ('germany', 'log_product_group_5_sales'),
        ('germany', 'log_product_group_6_sales'),
        ('germany', 'product_group_4_sales'),
        ('germany', 'united_kingdom_all_products_trade_usd_mil_top_5_import_partner'),
        ('germany', 'world_all_products_exports_in_usd_mil'),
        ('germany', 'world_capital_goods_export_usd_mil'),
        ('germany', 'world_consumer_goods_export_usd_mil'),
        ('germany', 'world_consumer_goods_import_usd_mil'),
        ('germany', 'world_raw_materials_export_usd_mil'),
        ('germany', 'world_transportation_export_usd_mil'),
        ('japan', 'n_products_imports'),
        ('world', 'electrical_equipment_production_index')
    ], 'product_group_5_sales': [
        ('china', 'germany_all_products_partner_share_top_5_import_partner'),
        ('china', 'germany_all_products_trade_usd_mil_top_5_import_partner'),
        ('germany', 'china_all_products_trade_usd_mil_top_5_import_partner'),
        ('germany', 'log_product_group_11_sales'),
        ('germany', 'log_product_group_1_sales'),
        ('germany', 'log_product_group_3_sales'),
        ('germany', 'log_product_group_4_sales'),
        ('germany', 'log_product_group_5_sales'),
        ('germany', 'log_product_group_6_sales'),
        ('germany', 'product_group_5_sales'),
        ('germany', 'united_kingdom_all_products_trade_usd_mil_top_5_import_partner'),
        ('germany', 'world_all_products_exports_in_usd_mil'),
        ('germany', 'world_capital_goods_export_usd_mil'),
        ('germany', 'world_consumer_goods_export_usd_mil'),
        ('germany', 'world_consumer_goods_import_product_share'),
        ('germany', 'world_raw_materials_export_usd_mil'),
        ('germany', 'world_transportation_export_usd_mil'),
        ('italy', 'n_partners_exports'),
        ('united states', 'n_products_exports'),
        ('world', 'electrical_equipment_production_index')
    ], 'product_group_3_sales': [
        ('china', 'production_index_machinery_electricals'),
        ('china', 'shipments_index_machinery_electricals'),
        ('europe', 'production_index_machinery_electricals'),
        ('france', 'shipments_index_machinery_electricals'),
        ('germany', 'log_product_group_11_sales'),
        ('germany', 'log_product_group_12_sales'),
        ('germany', 'log_product_group_13_sales'),
        ('germany', 'log_product_group_16_sales'),
        ('germany', 'log_product_group_1_sales'),
        ('germany', 'log_product_group_3_sales'),
        ('germany', 'log_product_group_4_sales'),
        ('germany', 'log_product_group_5_sales'),
        ('germany', 'log_product_group_6_sales'),
        ('germany', 'log_product_group_8_sales'),
        ('switzerland', 'electrical_equipment_production_index'),
        ('united kingdom', 'electrical_equipment_production_index'),
        ('united kingdom', 'machinery_and_equipment_nec_production_index'),
        ('united kingdom', 'production_index_machinery_electricals'),
        ('world', 'electrical_equipment_production_index'),
        ('world', 'machinery_and_equipment_nec_production_index')
    ], 'product_group_9_sales': [
        ('germany', 'log_product_group_14_sales'),
        ('germany', 'product_group_9_sales')
    ], 'product_group_14_sales': [
        ('china', 'germany_all_products_partner_share_top_5_import_partner'),
        ('china', 'germany_all_products_trade_usd_mil_top_5_import_partner'),
        ('france', 'germany_all_products_partner_share_top_5_import_partner'),
        ('germany', 'china_all_products_trade_usd_mil_top_5_import_partner'),
        ('germany', 'log_product_group_36_sales'),
        ('germany', 'log_product_group_9_sales'),
        ('germany', 'n_products_imports'),
        ('germany', 'product_group_14_sales'),
        ('germany', 'united_kingdom_all_products_trade_usd_mil_top_5_import_partner'),
        ('germany', 'world_all_products_exports_in_usd_mil'),
        ('germany', 'world_capital_goods_export_usd_mil'),
        ('germany', 'world_consumer_goods_export_product_share'),
        ('germany', 'world_consumer_goods_export_usd_mil'),
        ('germany', 'world_consumer_goods_import_product_share'),
        ('germany', 'world_consumer_goods_import_usd_mil'),
        ('germany', 'world_raw_materials_export_usd_mil'),
        ('germany', 'world_transportation_export_usd_mil'),
        ('italy', 'n_partners_exports'),
        ('japan', 'n_products_imports'),
        ('united states', 'n_products_exports')
    ], 'product_group_13_sales': [
        ('china', 'germany_all_products_partner_share_top_5_import_partner'),
        ('china', 'germany_all_products_trade_usd_mil_top_5_import_partner'),
        ('france', 'germany_all_products_partner_share_top_5_import_partner'),
        ('germany', 'china_all_products_trade_usd_mil_top_5_import_partner'),
        ('germany', 'log_product_group_4_sales'),
        ('germany', 'log_product_group_6_sales'),
        ('germany', 'n_products_imports'),
        ('germany', 'product_group_13_sales'),
        ('germany', 'united_kingdom_all_products_trade_usd_mil_top_5_import_partner'),
        ('germany', 'world_all_products_exports_in_usd_mil'),
        ('germany', 'world_capital_goods_export_usd_mil'),
        ('germany', 'world_consumer_goods_export_product_share'),
        ('germany', 'world_consumer_goods_export_usd_mil'),
        ('germany', 'world_consumer_goods_import_usd_mil'),
        ('germany', 'world_intermediate_goods_export_product_share'),
        ('germany', 'world_raw_materials_export_usd_mil'),
        ('germany', 'world_transportation_export_usd_mil'),
        ('italy', 'n_partners_exports'),
        ('united states', 'n_products_exports'),
        ('world', 'electrical_equipment_production_index')
    ], 'product_group_20_sales': [
        ('china', 'n_products_imports'),
        ('germany', 'log_product_group_12_sales'),
        ('germany', 'product_group_20_sales'),
        ('united kingdom', 'electrical_equipment_producer_prices'),
        ('united kingdom', 'n_products_imports'),
        ('united kingdom', 'shipments_index_machinery_electricals')
    ], 'product_group_36_sales': [
        ('china', 'n_partners_exports'),
        ('china', 'n_partners_imports'),
        ('france', 'n_partners_exports'),
        ('germany', 'china_all_products_trade_usd_mil_top_5_import_partner'),
        ('germany', 'n_partners_exports'),
        ('germany', 'product_group_36_sales'),
        ('germany', 'world_all_products_exports_in_usd_mil'),
        ('germany', 'world_capital_goods_export_usd_mil'),
        ('germany', 'world_intermediate_goods_export_product_share'),
        ('italy', 'n_partners_exports'),
        ('italy', 'n_partners_imports'),
        ('japan', 'n_partners_exports'),
        ('japan', 'n_partners_imports'),
        ('united kingdom', 'electrical_equipment_producer_prices'),
        ('united kingdom', 'n_partners_exports'),
        ('united kingdom', 'n_partners_imports'),
        ('united states', 'n_partners_exports'),
        ('united states', 'n_partners_imports'),
        ('world', 'n_partners_exports'),
        ('world', 'n_partners_imports')
    ]
}

MODEL_PARAMS = {
    'TimeSeriesETS': {
        'smoothing_level': [0.01, 0.1, 0.2, 0.5, 0.7, 0.9, 1.0],
        'smoothing_trend': [0.01, 0.1, 0.2, 0.5, 0.7, 0.9, 1.0],
        'smoothing_seasonal': [0.01, 0.1, 0.2, 0.5, 0.7, 0.9, 1.0],
        'trend': [None, "add", "mul"],
        'seasonal': [None, "add", "mul"],
        'seasonal_periods': [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        'damped_trend': [True, False]
    },
    
    'TimeSeriesXGB': {
    'n_estimators': [30, 50, 100, 150, 200],
    'max_depth': [3, 5, 7, 9, 12],
    'learning_rate': [0.01, 0.05, 0.1, 0.2],
    'subsample': [0.7, 0.8, 0.9, 1.0],
    'colsample_bytree': [0.6, 0.8, 1.0],
    'gamma': [0, 0.1, 0.2, 0.3],
    'batch_size': [16, 32, 64]
    }
}